server:
  port: 8081
spring:
  datasource:
    url: ${PG_DB:jdbc:postgresql://localhost:5432/banco}
    username: postgres
    password: 99433900
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  h2:
    console:
      enabled: false

microservice:
  address:
    url: "http://address:8082/api/address"
