spring:
  application:
    name: address-microservice

  cache:
    cache-names: 'address_cache'
    caffeine:
      spec: 'expireAfterAccess=5s'

  profiles:
    active: ${SCOPE:stage}

  kafka:
    bootstrap-servers: localhost:9092

feign:
  circuitbreaker:
    enabled: true
