name: PeopleMicroService
on:
  push:
    branches: [ master ]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
          cache: gradle

      - name: Build with Gradle
        run: ./gradlew compileJava

      - name: Create Jar
        run: ./gradlew assemble

      - name: Running test
        run: ./gradlew test

      - name: Docker login and push
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag warleyvods/pessoa-m

      - name: Docker Push
        run: docker push warleyvods/pessoa-m

      - name: Publish package
        uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
        with:
          arguments: publish --stacktrace
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
