name: PeopleMicroService
on:
  push:
    branches: [ master ]
env:
  GIT_LOGIN: ${{ secrets.GIT_LOGIN }}
  GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
  NEXUS_LOGIN: ${{ secrets.NEXUS_LOGIN }}
  NEXUS_PASS: ${{ secrets.NEXUS_PASS }}

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: "Say Hello Mona it's Monday"
        run: echo "Hoje $GIT_LOGIN"

      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
          cache: gradle

      - name: Build with Gradle
        run: ./gradlew compileJava

      - name: Create Jar
        run: ./gradlew assemble

      - name: Running test
        run: ./gradlew test

      - name: Docker login and push
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag warleyvods/pessoa-m

      - name: Docker Push
        run: docker push warleyvods/pessoa-m

      - name: Semantic Versioning
      - uses: paulhatch/semantic-version@v4.0.2
        with:
          tag_prefix: "v"
          # A string which, if present in a git commit, indicates that a change represents a
          # major (breaking) change, supports regular expressions wrapped with '/'
          major_pattern: "(MAJOR)"
          # Same as above except indicating a minor change, supports regular expressions wrapped with '/'
          minor_pattern: "(MINOR)"
          # A string to determine the format of the version output
          format: "${major}.${minor}.${patch}-prerelease${increment}"
          # Optional path to check for changes. If any changes are detected in the path the
          # 'changed' output will true. Enter multiple paths separated by spaces.
          change_path: "src/my-service"
          # Named version, will be used as suffix for name version tag
          namespace: people-ms
          # If this is set to true, *every* commit will be treated as a new version.
          bump_each_commit: false
          # If true, the body of commits will also be searched for major/minor patterns to determine the version type.
          search_commit_body: false
          # The output method used to generate list of users, 'csv' or 'json'.
          user_format_type: "csv"

      - name: Publish package
        uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
        with:
          arguments: publish
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}


